config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'


Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  root 'welcome#index'

  get 'search/search'

  resources :attachments, only: %i[destroy]

  resources :questions do
    resources :comments
    resources :answers do
      resources :comments
      member { patch :mark }
      member { patch :rate_up }
      member { patch :rate_down }
    end
    member { patch :subscribe }
    member { delete :unsubscribe }
  end

  mount ActionCable.server => '/cable'
end

app/views/layouts/_search_form.html.slim
= form_with(url: '/search/search', method: :get, scope: :search, local: true) do |f|
  = f.label :query, "Search for:"
  = f.select "search_type", options_for_select([ :questions, :answers, :comments, :users, :everything ])
  = f.text_field :query
  = f.submit "Search"

app/views/layouts/application.html.slim
html
  head
    title BastardOverflow
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag

    = javascript_include_tag "application"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"

  body
  
    = link_to 'Home ', welcome_index_path
    - if current_user.nil?
      = link_to 'Sign in', new_user_session_path
    - else
      = link_to 'Exit', destroy_user_session_path, method: :delete

    = render 'layouts/search_form'

    p class="notice"
      = notice 
    p class="alert"
      = alert

    = yield